# -*- coding: utf-8 -*-
"""Syntecxhub_Project_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oJTrdw3fyTOQN0ZA2Rszl2dCpuf_XxIM

## Creating dirty data ##
"""

import pandas as pd
import numpy as np

D_data = {
    " Student Name ": ["Amit", "Riya", "Amit", "John", "Sara", None, "Riya"],
    "English Marks": [78, 85, 78, np.nan, 88, 67, 85],
    "Maths Marks": ["85", "90", "85", "70", None, "60", "90"],
    "Science Marks": [88, 92, 88, 72, 84, 58, 92],
    "Exam Date": ["2024-03-01", "01-03-2024", "2024-03-01", "2024/03/02", None, "2024-03-03", "01-03-2024"]
}

data = pd.DataFrame(D_data)

print(data.head(7))

# Finding nulls
print("Total nulls:",data.isnull().sum())

# Handling nulls, converting type
data[' Student Name '] = data[' Student Name '].fillna("Unknow")
data['English Marks'] = data['English Marks'].fillna(data['English Marks'].mean())
data['Maths Marks'] = pd.to_numeric(data['Maths Marks'],errors='coerce')
data['Maths Marks'] = data['Maths Marks'].fillna(data['Maths Marks'].mean())
data['Exam Date'] = pd.to_datetime(data['Exam Date'],errors='coerce')
data['Exam Date'] = data['Exam Date'].fillna(data['Exam Date'].mode()[0])

print("Total Duplicates:",data.duplicated().sum())
c_data = data.drop_duplicates()
print(c_data)

c_data.columns = (c_data.columns.str.strip().str.lower().str.replace(" ","_"))

"""## Save Cleaned Dataset ##"""

c_data.to_excel("c_data.xlsx",index=False)